language: node_js
node_js:
  - "0.12"
branches:
  only:
    - master
env:
  global:
    - SRC_DIR: dist
    - DEPLOY_BRANCH: gh-pages
    - DEPLOY_DIR: _deploy
    - GIT_NAME: "Helior Colorado"
    - GIT_EMAIL: me@helior.info
    - GH_OWNER: helior
    - GH_PROJECT: places.helior.info
script: make build
after_success:
  - git clone -b "$DEPLOY_BRANCH" https://"$GH_OAUTH_TOKEN"@github.com/"$GH_OWNER"/"$GH_PROJECT" "$DEPLOY_DIR" > /dev/null 2>&1
  - cd "$DEPLOY_DIR"
  - git checkout "$DEPLOY_BRANCH" || git checkout -b "$DEPLOY_BRANCH"
  - git rm -r .
  - cp -R ../"$SRC_DIR"/* .
  - cp ../"$SRC_DIR"/.* .
  - git add -f .
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name "$GIT_NAME"
  - git commit -am "Travis deploying $TRAVIS_COMMIT_RANGE to $DEPLOY_BRANCH"
  - git push https://"$GH_OAUTH_TOKEN"@github.com/"$GH_OWNER"/"$GH_PROJECT" HEAD:"$DEPLOY_BRANCH" > /dev/null 2>&1
